{"uuid": "8fa6f3d5-0e36-42fe-9fe5-1e4d4b3419a8", "children": ["ec472832-9d49-45e7-afb0-718c7fb12f5c", "facf751d-753a-4860-8b10-7fc380b4bc3f", "f6b98833-87f8-47f2-931d-a9055b8f79f6", "41a53a58-bfbd-4928-8039-4c7d2b5e853f", "0d466fec-9f48-45c5-bf3f-9896d537b317", "925e26ee-8adf-48e9-8d65-ee6d90ad7ee5", "656bac82-ae4a-4608-8f6b-e767cb59f2a9", "0b2c7d53-ba79-4632-86a4-0fd61f7237f0", "c3cf73ba-1e60-4774-abf0-d70b3172b545", "6cf5cbd7-bff4-45f2-b508-49381cb1a6f8", "b07fdc80-5633-44b2-83a0-06ccbafe86d8", "3d717ef2-ae37-45a7-b6c8-41b2396b2325", "37d56fc5-0ab2-40fd-9ab5-524f60540c43", "dadcf80f-dba6-4d6f-bd5f-336d85ed882e", "091a9be3-4a4f-46f8-8d2f-0b5144cecb3d", "c22b369d-96fd-4b83-a30d-a87b372828b8", "a6696c3d-fa4e-4aea-8b71-41262b6b2d09", "b5059e82-63f3-4042-85a3-8adbdbaa55a9", "34fa0f81-9e06-4eec-b481-72570b5f0ed4", "35d3a273-498d-4f7d-aaf3-4550373f0fb4", "bef9def4-f9f8-42cb-80e0-489f0a79cc49"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=108.0.5359.125)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00C3ACD3+2075859]\n\tOrdinal0 [0x00BCEE61+1633889]\n\tOrdinal0 [0x00ACB7BD+571325]\n\tOrdinal0 [0x00AB2E1A+470554]\n\tOrdinal0 [0x00B1AA0B+895499]\n\tOrdinal0 [0x00B2AC96+961686]\n\tOrdinal0 [0x00B17136+880950]\n\tOrdinal0 [0x00AEFEFD+720637]\n\tOrdinal0 [0x00AF0F3F+724799]\n\tGetHandleVerifier [0x00EEEED2+2769538]\n\tGetHandleVerifier [0x00EE0D95+2711877]\n\tGetHandleVerifier [0x00CCA03A+521194]\n\tGetHandleVerifier [0x00CC8DA0+516432]\n\tOrdinal0 [0x00BD682C+1665068]\n\tOrdinal0 [0x00BDB128+1683752]\n\tOrdinal0 [0x00BDB215+1683989]\n\tOrdinal0 [0x00BE6484+1729668]\n\tBaseThreadInitThunk [0x76416BD9+25]\n\tRtlGetFullPathName_UEx [0x779B8FD2+1218]\n\tRtlGetFullPathName_UEx [0x779B8F9D+1165]\n\n", "trace": "  File \"C:\\python309\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\python309\\lib\\site-packages\\_pytest\\fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\python309\\lib\\site-packages\\_pytest\\fixtures.py\", line 907, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\test\\autoTest\\NZYMS\\TestCase\\conftest.py\", line 11, in driver\n    login.geturl(config.host)\n  File \"D:\\autoTest\\autoTest\\Base\\basepage.py\", line 103, in geturl\n    self.driver.maximize_window()\n  File \"C:\\python309\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 607, in maximize_window\n    self.execute(command, None)\n  File \"C:\\python309\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\python309\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1673339995081, "stop": 1673340000732}], "start": 1673339995081, "stop": 1673340002539}